/** Tempo server. PostgreSQL stores product data and durable sign-in sessions. */
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const db = require('./db');
const { generatePlan, localParts, dateKey } = require('./plan-engine');
const { createCoachReply, interpretCoachAction } = require('./coach');
const { buildFitnessSummary } = require('./fitness-summary');
const feedbackRecipient = process.env.FEEDBACK_RECIPIENT_EMAIL || 'kwhin03@gmail.com';
const strava = require('./strava');

const PORT = Number(process.env.PORT || 3000);
const ROOT = __dirname;
const stravaStates = new Map();
const SESSION_DAYS = 14;
const isProduction = process.env.NODE_ENV === 'production';
const rateWindows = new Map();

function passwordHash(password, salt = crypto.randomBytes(16).toString('hex')) { return `${salt}:${crypto.scryptSync(password, salt, 64).toString('hex')}`; }
function passwordMatches(password, stored) { const [salt, savedHash] = stored.split(':'); return crypto.timingSafeEqual(Buffer.from(savedHash, 'hex'), Buffer.from(passwordHash(password, salt).split(':')[1], 'hex')); }
function publicUser(user) { const { passwordHash: _passwordHash, ...safeUser } = user; return safeUser; }
function parseCookies(request) { return Object.fromEntries((request.headers.cookie || '').split(';').filter(Boolean).map(item => { const index = item.indexOf('='); return [item.slice(0, index).trim(), decodeURIComponent(item.slice(index + 1))]; })); }
async function currentUser(request) { const userId = await db.getSessionUserId(parseCookies(request).tempo_session); return userId ? db.getUserById(userId) : null; }
function json(response, status, body, cookie) { response.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store', 'X-Content-Type-Options': 'nosniff', ...(cookie ? { 'Set-Cookie': cookie } : {}) }); response.end(JSON.stringify(body)); }
function readJson(request) { return new Promise((resolve, reject) => { let raw = ''; request.on('data', chunk => { raw += chunk; if (raw.length > 100000) request.destroy(); }); request.on('end', () => { try { resolve(raw ? JSON.parse(raw) : {}); } catch { reject(new Error('Please send valid JSON.')); } }); }); }
async function requireUser(request, response) { const user = await currentUser(request); if (!user) { json(response, 401, { error: 'Please sign in first.' }); return null; } return user; }
function validateProfile(profile) { const goals = ['run_stronger', 'build_strength', 'both', 'lose_weight', 'general_fitness'], levels = ['new', 'intermediate', 'advanced'], equipment = ['bodyweight', 'home_gym', 'full_gym']; if (!goals.includes(profile.goal)) return 'Choose a valid training goal.'; if (!levels.includes(profile.trainingLevel)) return 'Choose a valid training level.'; if (!equipment.includes(profile.equipment)) return 'Choose valid equipment access.'; if (!Array.isArray(profile.trainingDays) || profile.trainingDays.length < 1 || profile.trainingDays.length > 7) return 'Choose one to seven training days.'; if (!profile.timezone || profile.timezone.length > 80) return 'Provide a valid timezone.'; if (typeof profile.healthConsent !== 'boolean' || typeof profile.aiConsent !== 'boolean') return 'Choose the profile consent options.'; return null; }
function validateWorkout(workout) { const outcomes = ['completed', 'partial', 'skipped']; if (!String(workout.title || '').trim()) return 'Give the workout a short name.'; if (!outcomes.includes(workout.outcome)) return 'Choose whether the workout was completed, partial, or skipped.'; const duration = Number(workout.durationMinutes); if (!Number.isFinite(duration) || duration < 0 || duration > 360) return 'Enter a duration from 0 to 360 minutes.'; const effort = workout.perceivedEffort === '' || workout.perceivedEffort === undefined ? null : Number(workout.perceivedEffort); if (effort !== null && (!Number.isInteger(effort) || effort < 1 || effort > 10)) return 'Effort must be a whole number from 1 to 10.'; if (String(workout.note || '').length > 500) return 'Keep notes to 500 characters or fewer.'; return null; }
function validateWorkoutDetails(details) { if (!details || typeof details !== 'object' || Array.isArray(details)) return null; const lifts = details.lifts || []; if (!Array.isArray(lifts) || lifts.length > 50) return 'Add up to 50 lifting exercises.'; for (const lift of lifts) { if (!String(lift.exercise || '').trim() || String(lift.exercise).length > 80) return 'Give each lifting exercise a short name.'; if (!Number.isInteger(Number(lift.sets)) || Number(lift.sets) < 1 || Number(lift.sets) > 100) return 'Sets must be a whole number from 1 to 100.'; if (!Number.isInteger(Number(lift.reps)) || Number(lift.reps) < 1 || Number(lift.reps) > 1000) return 'Reps must be a whole number from 1 to 1000.'; if (String(lift.weight || '').length > 30) return 'Keep each weight entry under 30 characters.'; } const running = details.running || {}; if (running.distance !== undefined && running.distance !== '' && (!Number.isFinite(Number(running.distance)) || Number(running.distance) < 0 || Number(running.distance) > 500)) return 'Distance must be between 0 and 500 miles.'; if (running.averageHeartRate !== undefined && running.averageHeartRate !== '' && (!Number.isInteger(Number(running.averageHeartRate)) || Number(running.averageHeartRate) < 20 || Number(running.averageHeartRate) > 250)) return 'Average heart rate must be between 20 and 250.'; if (String(running.averagePace || '').length > 30) return 'Keep average pace under 30 characters.'; return null; }
function sessionCookie(id) { return `tempo_session=${id}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${SESSION_DAYS * 86400}${isProduction ? '; Secure' : ''}`; }
function clearSessionCookie() { return `tempo_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0${isProduction ? '; Secure' : ''}`; }
function clientIp(request) { return String(request.headers['x-forwarded-for'] || request.socket.remoteAddress || 'unknown').split(',')[0].trim(); }
function allowRequest(request, response, key, max, windowMs) { const now = Date.now(), bucketKey = `${key}:${clientIp(request)}`, hits = (rateWindows.get(bucketKey) || []).filter(time => time > now - windowMs); if (hits.length >= max) { json(response, 429, { error: 'Please wait a moment before trying again.' }); return false; } hits.push(now); rateWindows.set(bucketKey, hits); return true; }
async function createUserSession(userId) { const id = crypto.randomBytes(32).toString('hex'), expiresAt = new Date(Date.now() + SESSION_DAYS * 86400000); await db.createSession(id, userId, expiresAt); return id; }
async function syncStrava(userId) { const connection = await db.getStravaConnection(userId); if (!connection) throw new Error('Connect Strava first.'); const access = await strava.refreshIfNeeded(connection); if (access.refreshed) await db.upsertStravaConnection(userId, { ...access.refreshed, athleteId: connection.athleteId, scope: connection.scope }); const activities = await strava.listActivities(access.accessToken); let imported = 0; for (const activity of activities) { if (await db.hasStravaActivity(activity.id)) continue; const minutes = Math.max(0, Math.round(Number(activity.moving_time || activity.elapsed_time || 0) / 60)), sport = activity.sport_type || activity.type || 'activity', isRun = /run/i.test(sport), distanceMiles = Number(activity.distance || 0) * 0.000621371; const workout = await db.addWorkout(userId, { id: crypto.randomUUID(), title: activity.name || 'Strava activity', type: sport, outcome: 'completed', durationMinutes: minutes, perceivedEffort: null, note: 'Imported from Strava', details: isRun && distanceMiles ? { running: { distance: Math.round(distanceMiles * 100) / 100, averageHeartRate: activity.average_heartrate ? Math.round(activity.average_heartrate) : '' } } : {}, source: 'strava', loggedAt: activity.start_date || new Date().toISOString() }); await db.addStravaActivity(userId, activity, workout.id); imported++; } return imported; }
async function planWithDashboard(user) { const workouts = await db.getWorkouts(user.id); const draft = generatePlan(user.profile, { missedToday: user.missedToday, workouts }); const overrides = await db.getPlanOverrides(user.id, draft.weekStart, draft.weekEnd); const tempoCheck = await db.getDailyCheckin(user.id, draft.today.date); const plan = generatePlan(user.profile, { missedToday: user.missedToday, workouts, overrides, tempoCheck }); const activity = await db.getActivityDashboard(user.id, plan.weekStart, plan.weekEnd, plan.today.date); const fitnessSummary = buildFitnessSummary(workouts, { timezone: user.profile.timezone }); return { ...plan, dashboard: activity, tempoCheck, fitnessSummary, weeklyWin: weeklyWin(plan, workouts) }; }
function dashboardWindow(timezone, requestedRange) {
  const range = ['week', 'month', 'year', 'ytd'].includes(requestedRange) ? requestedRange : 'week';
  const today = localParts(new Date(), timezone || 'UTC');
  const end = dateKey(today);
  let start;
  if (range === 'week') { const offset = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].indexOf(today.weekday); const date = new Date(Date.UTC(today.year, today.month - 1, today.day - offset)); start = date.toISOString().slice(0, 10); }
  else if (range === 'month') start = `${today.year}-${String(today.month).padStart(2, '0')}-01`;
  else if (range === 'year') { const date = new Date(Date.UTC(today.year - 1, today.month - 1, today.day)); start = date.toISOString().slice(0, 10); }
  else start = `${today.year}-01-01`;
  return { range, start, end };
}
function weeklyWin(plan, workouts) {
  const completed = workouts.filter(workout => workout.outcome === 'completed' && (() => { const date = dateKey(localParts(new Date(workout.loggedAt), plan.timezone)); return date >= plan.weekStart && date <= plan.weekEnd; })());
  const miles = completed.reduce((total, workout) => total + Number(workout.details?.running?.distance || 0), 0);
  const liftingSets = completed.reduce((total, workout) => total + (workout.details?.lifts || []).reduce((sets, lift) => sets + Number(lift.sets || 0), 0), 0);
  if (miles > 0) return `You logged ${miles.toFixed(miles < 10 ? 1 : 0)} running mile${miles === 1 ? '' : 's'} this week. That is real forward motion.`;
  if (liftingSets > 0) return `You completed ${liftingSets} lifting set${liftingSets === 1 ? '' : 's'} this week. Strong work, one set at a time.`;
  if (completed.length > 0) return `You completed ${completed.length} workout${completed.length === 1 ? '' : 's'} this week. Consistency is the win.`;
  return 'Your win this week is setting a plan that fits your life. Your next small step is waiting.';
}

async function resolveCoachConversation(userId, conversationId) {
  if (!conversationId) return db.getLatestCoachConversation(userId);
  return db.getCoachConversation(userId, String(conversationId));
}

async function handleApi(request, response, url) {
  if (request.method === 'GET' && url.pathname === '/api/coach/conversations') {
    const user = await requireUser(request, response); if (!user) return;
    return json(response, 200, { conversations: await db.getCoachConversations(user.id) });
  }
  if (request.method === 'POST' && url.pathname === '/api/coach/conversations') {
    const user = await requireUser(request, response); if (!user) return;
    return json(response, 201, { conversation: await db.createCoachConversation(user.id) });
  }
  if (request.method === 'DELETE' && /^\/api\/coach\/conversations\/[0-9a-f-]{36}$/i.test(url.pathname)) {
    const user = await requireUser(request, response); if (!user) return;
    const conversationId = url.pathname.split('/').pop();
    if (!await db.deleteCoachConversation(user.id, conversationId)) return json(response, 404, { error: 'That coach conversation was not found.' });
    return json(response, 200, { ok: true });
  }
  if (request.method === 'GET' && url.pathname === '/api/coach') {
    const user = await requireUser(request, response); if (!user) return;
    const conversation = await resolveCoachConversation(user.id, url.searchParams.get('conversationId'));
    if (!conversation) return json(response, 404, { error: 'That coach conversation was not found.' });
    return json(response, 200, { conversation, messages: await db.getCoachMessages(user.id, conversation.id), mode: process.env.OPENAI_API_KEY && user.profile?.aiConsent ? 'ai' : 'preview' });
  }
  if (request.method === 'POST' && url.pathname === '/api/coach') {
    let user = await requireUser(request, response); if (!user) return;
    if (!allowRequest(request, response, 'coach', 24, 60000)) return;
    if (!user.profile) return json(response, 400, { error: 'Save your coaching profile before talking with Tempo Coach.' });
    const body = await readJson(request), message = String(body.message || '').trim();
    if (!message || message.length > 600) return json(response, 400, { error: 'Enter a message between 1 and 600 characters.' });
    const conversation = await resolveCoachConversation(user.id, body.conversationId);
    if (!conversation) return json(response, 404, { error: 'That coach conversation was not found.' });
    await db.addCoachMessage(user.id, conversation.id, 'user', message);
    let plan = await planWithDashboard(user), actionSummary = '';
    const action = interpretCoachAction(message, plan, user.profile);
    if (action?.type === 'miss_today') { Object.assign(user, await db.markMissedToday(user.id)); actionSummary = 'Tempo marked today as unavailable and re-spaced the remaining plan.'; }
    else if (action?.type === 'tempo_check') { const existingCheckin = await db.getDailyCheckin(user.id, plan.today.date); const checkin = { availableMinutes: action.availableMinutes || existingCheckin?.availableMinutes || [12, 20, 45, 90].reduce((closest, option) => Math.abs(option - user.profile.sessionMinutes) < Math.abs(closest - user.profile.sessionMinutes) ? option : closest, 45), energy: action.energy || existingCheckin?.energy || 'normal', trainingMode: action.trainingMode || existingCheckin?.trainingMode || 'auto', setup: action.setup || existingCheckin?.setup || 'auto' }; await db.upsertDailyCheckin(user.id, plan.today.date, checkin); actionSummary = `Tempo updated today: ${checkin.availableMinutes} minutes, ${checkin.energy} energy${checkin.trainingMode !== 'auto' ? `, ${checkin.trainingMode}` : ''}${checkin.setup !== 'auto' ? `, ${checkin.setup.replace('_', ' ')}` : ''}.`; }
    else if (action?.type === 'workout_swap') { await db.upsertPlanOverride(user.id, plan.today.date, action.alternative); actionSummary = `Tempo changed today’s workout to ${action.alternative.title}.`; }
    else if (action?.type === 'log_run') { await db.addWorkout(user.id, { id: crypto.randomUUID(), title: 'Run', type: 'running', outcome: 'completed', durationMinutes: Math.max(0, Math.min(360, action.minutes)), perceivedEffort: action.effort, note: 'Logged through Tempo Coach', details: { running: { distance: action.miles } }, source: 'manual', loggedAt: new Date().toISOString() }); actionSummary = `Tempo logged a ${action.miles}-mile run${action.effort ? ` at effort ${action.effort}` : ''}.`; }
    else if (action?.type === 'training_days') { Object.assign(user, await db.upsertProfile(user.id, { ...user.profile, trainingDays: action.trainingDays })); actionSummary = `Tempo changed your preferred training days to ${action.trainingDays.join(', ')}.`; }
    else if (action?.type === 'training_goal') { Object.assign(user, await db.upsertProfile(user.id, { ...user.profile, goal: action.goal })); actionSummary = `Tempo updated your training focus to ${action.goal === 'run_stronger' ? 'running' : action.goal === 'build_strength' ? 'lifting' : 'hybrid training'}.`; }
    else if (action?.type === 'session_minutes') { Object.assign(user, await db.upsertProfile(user.id, { ...user.profile, sessionMinutes: action.sessionMinutes })); actionSummary = `Tempo set your normal session length to about ${action.sessionMinutes} minutes.`; }
    else if (action?.type === 'equipment') { Object.assign(user, await db.upsertProfile(user.id, { ...user.profile, equipment: action.equipment })); actionSummary = `Tempo updated your equipment to ${action.equipment === 'bodyweight' ? 'bodyweight only' : action.equipment === 'home_gym' ? 'a home gym' : 'a full gym'}.`; }
    else if (action?.type === 'training_location') { Object.assign(user, await db.upsertProfile(user.id, { ...user.profile, trainingLocation: action.trainingLocation })); actionSummary = `Tempo updated your running location preference to ${action.trainingLocation}.`; }
    else if (action?.type === 'log_lift') { await db.addWorkout(user.id, { id: crypto.randomUUID(), title: action.exercise, type: 'lifting', outcome: 'completed', durationMinutes: 0, perceivedEffort: null, note: 'Logged through Tempo Coach', details: { lifts: [{ exercise: action.exercise, sets: action.sets, reps: action.reps, weight: action.weight }] }, source: 'manual', loggedAt: new Date().toISOString() }); actionSummary = `Tempo logged ${action.sets} × ${action.reps} ${action.exercise}${action.weight ? ` at ${action.weight}` : ''}.`; }
    else if (action?.type === 'log_walk') { await db.addWorkout(user.id, { id: crypto.randomUUID(), title: 'Walk', type: 'recovery', outcome: 'completed', durationMinutes: action.minutes, perceivedEffort: null, note: 'Logged through Tempo Coach', details: {}, source: 'manual', loggedAt: new Date().toISOString() }); actionSummary = `Tempo logged a ${action.minutes}-minute walk.`; }
    else if (action?.type === 'complete_today') { await db.addWorkout(user.id, { id: crypto.randomUUID(), title: action.session.title, type: action.session.type, outcome: 'completed', durationMinutes: action.session.minutes, perceivedEffort: null, note: 'Completed through Tempo Coach', details: {}, source: 'plan', loggedAt: new Date().toISOString() }); actionSummary = `Tempo marked today’s ${action.session.title} complete.`; }
    plan = await planWithDashboard(user);
    const workouts = await db.getWorkouts(user.id), messages = await db.getCoachMessages(user.id, conversation.id);
    const reply = await createCoachReply({ user, plan, workouts, messages, message, actionSummary });
    const assistant = await db.addCoachMessage(user.id, conversation.id, 'assistant', actionSummary ? `${actionSummary} ${reply.content}` : reply.content);
    return json(response, 200, { conversation, message: assistant, mode: reply.mode, action: action?.type || null });
  }
  if (request.method === 'GET' && url.pathname === '/api/me') { const user = await currentUser(request); return json(response, 200, { user: user ? publicUser(user) : null }); }
  if (request.method === 'POST' && url.pathname === '/api/auth/register') {
    if (!allowRequest(request, response, 'register', 5, 3600000)) return;
    const { name = '', email = '', password = '', adultConfirmation = false } = await readJson(request); const normalizedEmail = email.trim().toLowerCase();
    if (name.trim().length < 2) return json(response, 400, { error: 'Enter your name (at least 2 characters).' }); if (!/^\S+@\S+\.\S+$/.test(normalizedEmail)) return json(response, 400, { error: 'Enter a valid email address.' }); if (password.length < 10) return json(response, 400, { error: 'Use at least 10 characters for your password.' }); if (adultConfirmation !== true) return json(response, 400, { error: 'Tempo beta is currently for people 18 or older.' });
    if (await db.getUserByEmail(normalizedEmail)) return json(response, 409, { error: 'An account with that email already exists.' });
    const user = await db.createUser({ id: crypto.randomUUID(), name: name.trim(), email: normalizedEmail, passwordHash: passwordHash(password), role: 'consumer', createdAt: new Date().toISOString() }); const sessionId = await createUserSession(user.id); return json(response, 201, { user: publicUser(user) }, sessionCookie(sessionId));
  }
  if (request.method === 'POST' && url.pathname === '/api/auth/login') { if (!allowRequest(request, response, 'login', 10, 900000)) return; const { email = '', password = '' } = await readJson(request); const user = await db.getUserByEmail(email.trim().toLowerCase()); if (!user || !passwordMatches(password, user.passwordHash)) return json(response, 401, { error: 'Email or password is incorrect.' }); const sessionId = await createUserSession(user.id); return json(response, 200, { user: publicUser(user) }, sessionCookie(sessionId)); }
  if (request.method === 'POST' && url.pathname === '/api/auth/logout') { await db.deleteSession(parseCookies(request).tempo_session); return json(response, 200, { ok: true }, clearSessionCookie()); }
  if (request.method === 'DELETE' && url.pathname === '/api/account') { const user = await requireUser(request, response); if (!user) return; await db.deleteUser(user.id); return json(response, 200, { ok: true }, clearSessionCookie()); }
  if (request.method === 'PUT' && url.pathname === '/api/profile') { const user = await requireUser(request, response); if (!user) return; const submitted = await readJson(request); const profile = { ...submitted, trainingLocation: ['indoor', 'outdoor', 'both'].includes(submitted.trainingLocation) ? submitted.trainingLocation : 'both' }, problem = validateProfile(profile); if (problem) return json(response, 400, { error: problem }); const saved = await db.upsertProfile(user.id, { ...profile, sessionMinutes: Number(profile.sessionMinutes) || 45, constraints: profile.healthConsent ? String(profile.constraints || '').slice(0, 1000) : '' }); return json(response, 200, { user: publicUser(saved) }); }
  if (request.method === 'GET' && url.pathname === '/api/plan') { const user = await requireUser(request, response); if (!user) return; if (!user.profile) return json(response, 400, { error: 'Save your coaching profile before generating a plan.' }); return json(response, 200, { plan: await planWithDashboard(user) }); }
  if (request.method === 'POST' && url.pathname === '/api/plan/miss-today') { const user = await requireUser(request, response); if (!user) return; if (!user.profile) return json(response, 400, { error: 'Save your coaching profile before adjusting a plan.' }); const saved = await db.markMissedToday(user.id); return json(response, 200, { plan: await planWithDashboard(saved) }); }
  if (request.method === 'POST' && url.pathname === '/api/checkin') { const user = await requireUser(request, response); if (!user) return; if (!user.profile) return json(response, 400, { error: 'Save your coaching profile before using Tempo Check.' }); const body = await readJson(request), availableMinutes = Number(body.availableMinutes), energy = String(body.energy || 'normal'), trainingMode = String(body.trainingMode || 'auto'), setup = String(body.setup || 'auto'); if (![12, 20, 45, 90].includes(availableMinutes) || !['low', 'normal', 'high'].includes(energy) || !['auto', 'running', 'lifting'].includes(trainingMode) || !['auto', 'gym', 'no_gym', 'indoor', 'outdoor'].includes(setup)) return json(response, 400, { error: 'Choose valid time, workout, and location options.' }); const draft = generatePlan(user.profile, { missedToday: user.missedToday, workouts: await db.getWorkouts(user.id) }); await db.upsertDailyCheckin(user.id, draft.today.date, { availableMinutes, energy, trainingMode, setup }); return json(response, 200, { plan: await planWithDashboard(user) }); }
  if (request.method === 'POST' && url.pathname === '/api/plan/override') { const user = await requireUser(request, response); if (!user) return; if (!user.profile) return json(response, 400, { error: 'Save your coaching profile before changing a plan.' }); const body = await readJson(request); const plan = await planWithDashboard(user); const session = plan.sessions.find(item => item.date === String(body.date || '')); if (!session || !['today', 'upcoming'].includes(session.status)) return json(response, 400, { error: 'Only today and future sessions can be changed.' }); const alternative = session.alternatives.find(item => item.id === String(body.alternativeId || '')); if (!alternative) return json(response, 400, { error: 'Choose one of the recommended workout options.' }); await db.upsertPlanOverride(user.id, session.date, alternative); return json(response, 200, { plan: await planWithDashboard(user) }); }
  if (request.method === 'GET' && url.pathname === '/api/dashboard') { const user = await requireUser(request, response); if (!user) return; if (!user.profile) return json(response, 400, { error: 'Save your coaching profile before viewing your dashboard.' }); const window = dashboardWindow(user.profile.timezone, url.searchParams.get('range')); return json(response, 200, { dashboard: await db.getDashboardRange(user.id, window.start, window.end), ...window }); }
  if (request.method === 'GET' && url.pathname === '/api/fitness-summary') { const user = await requireUser(request, response); if (!user) return; const workouts = await db.getWorkouts(user.id); return json(response, 200, { fitnessSummary: buildFitnessSummary(workouts, { timezone: user.profile?.timezone || 'UTC' }) }); }
  if (request.method === 'GET' && url.pathname === '/api/workouts') { const user = await requireUser(request, response); if (!user) return; return json(response, 200, { workouts: await db.getWorkouts(user.id) }); }
  if (request.method === 'POST' && url.pathname === '/api/workouts') { const user = await requireUser(request, response); if (!user) return; const workout = await readJson(request); workout.title = String(workout.title || '').trim() || 'Workout'; const problem = validateWorkout(workout) || validateWorkoutDetails(workout.details); if (problem) return json(response, 400, { error: problem }); const loggedDate = workout.loggedAt ? new Date(`${workout.loggedAt}T12:00:00`) : new Date(); if (Number.isNaN(loggedDate) || loggedDate > new Date(Date.now() + 86400000) || loggedDate < new Date('2010-01-01')) return json(response, 400, { error: 'Choose a valid activity date that is not in the future.' }); const saved = await db.addWorkout(user.id, { id: crypto.randomUUID(), title: String(workout.title).trim().slice(0, 80), type: String(workout.type || 'other').slice(0, 40), outcome: workout.outcome, durationMinutes: Number(workout.durationMinutes), perceivedEffort: workout.perceivedEffort === '' || workout.perceivedEffort === undefined ? null : Number(workout.perceivedEffort), note: String(workout.note || '').trim().slice(0, 500), details: workout.details || {}, source: workout.source === 'plan' ? 'plan' : 'manual', loggedAt: loggedDate.toISOString() }); return json(response, 201, { workout: saved }); }
  if (request.method === 'PUT' && /^\/api\/workouts\/[0-9a-f-]{36}$/i.test(url.pathname)) { const user = await requireUser(request, response); if (!user) return; const workoutId = url.pathname.split('/').pop(); const existing = (await db.getWorkouts(user.id)).find(item => item.id === workoutId); if (!existing) return json(response, 404, { error: 'That activity could not be found.' }); if (existing.source === 'strava') return json(response, 403, { error: 'Strava activities are read-only in Tempo. Correct it in Strava, then sync again.' }); const workout = await readJson(request); workout.title = String(workout.title || '').trim() || 'Workout'; const problem = validateWorkout(workout) || validateWorkoutDetails(workout.details); if (problem) return json(response, 400, { error: problem }); const loggedDate = workout.loggedAt ? new Date(`${workout.loggedAt}T12:00:00`) : new Date(); if (Number.isNaN(loggedDate) || loggedDate > new Date(Date.now() + 86400000) || loggedDate < new Date('2010-01-01')) return json(response, 400, { error: 'Choose a valid activity date that is not in the future.' }); const saved = await db.updateWorkout(user.id, { id: workoutId, title: String(workout.title).trim().slice(0, 80), type: String(workout.type || 'other').slice(0, 40), outcome: workout.outcome, durationMinutes: Number(workout.durationMinutes), perceivedEffort: workout.perceivedEffort === '' || workout.perceivedEffort === undefined ? null : Number(workout.perceivedEffort), note: String(workout.note || '').trim().slice(0, 500), details: workout.details || {}, loggedAt: loggedDate.toISOString() }); return json(response, 200, { workout: saved }); }
  if (request.method === 'POST' && url.pathname === '/api/tester-feedback') { const user = await requireUser(request, response); if (!user) return; if (!allowRequest(request, response, 'feedback', 8, 3600000)) return; const message = String((await readJson(request)).message || '').trim(); if (message.length < 5 || message.length > 2000) return json(response, 400, { error: 'Please enter feedback between 5 and 2,000 characters.' }); const feedback = await db.addTesterFeedback(user.id, message); const subject = encodeURIComponent('Tempo beta feedback'); const body = encodeURIComponent(`Tempo beta feedback\n\nFrom: ${user.name} (${user.email})\n\n${message}`); return json(response, 201, { feedback, mailto: `mailto:${feedbackRecipient}?subject=${subject}&body=${body}` }); }
  if (request.method === 'GET' && url.pathname === '/api/friends') { const user = await requireUser(request, response); if (!user) return; const relationships = await db.getFriendships(user.id); const friends = relationships.filter(item => item.status === 'accepted'); const incoming = relationships.filter(item => item.status === 'pending' && item.recipientId === user.id); const activities = await db.getFriendActivities(friends.map(friend => friend.requesterId === user.id ? friend.recipientId : friend.requesterId)); return json(response, 200, { friends, incoming, activities }); }
  if (request.method === 'POST' && url.pathname === '/api/friends/request') { const user = await requireUser(request, response); if (!user) return; const body = await readJson(request), email = String(body.email || '').trim().toLowerCase(); if (!/^\S+@\S+\.\S+$/.test(email)) return json(response, 400, { error: 'Enter your friend’s account email address.' }); const recipient = await db.getUserByEmail(email); if (!recipient) return json(response, 404, { error: 'No Tempo account uses that email yet.' }); if (recipient.id === user.id) return json(response, 400, { error: 'You cannot add your own account.' }); const existing = await db.getFriendships(user.id); if (existing.some(item => item.email === email)) return json(response, 409, { error: 'You already have a request or connection with this person.' }); await db.createFriendRequest(user.id, recipient.id); return json(response, 201, { ok: true }); }
  if (request.method === 'POST' && url.pathname === '/api/friends/accept') { const user = await requireUser(request, response); if (!user) return; const body = await readJson(request); if (!await db.acceptFriendRequest(user.id, String(body.requestId || ''))) return json(response, 404, { error: 'Friend request not found.' }); return json(response, 200, { ok: true }); }
  if (request.method === 'GET' && url.pathname === '/api/coach') { const user = await requireUser(request, response); if (!user) return; return json(response, 200, { messages: await db.getCoachMessages(user.id), mode: process.env.OPENAI_API_KEY && user.profile?.aiConsent ? 'ai' : 'preview' }); }
  if (request.method === 'POST' && url.pathname === '/api/coach') { const user = await requireUser(request, response); if (!user) return; if (!user.profile) return json(response, 400, { error: 'Save your coaching profile before talking with Tempo Coach.' }); const body = await readJson(request); const message = String(body.message || '').trim(); if (!message || message.length > 600) return json(response, 400, { error: 'Enter a message between 1 and 600 characters.' }); await db.addCoachMessage(user.id, 'user', message); let plan = await planWithDashboard(user), actionSummary = ''; const action = interpretCoachAction(message, plan); if (action?.type === 'miss_today') { Object.assign(user, await db.markMissedToday(user.id)); actionSummary = 'Tempo marked today as unavailable and re-spaced the remaining plan.'; } else if (action?.type === 'tempo_check') { await db.upsertDailyCheckin(user.id, plan.today.date, { availableMinutes: action.availableMinutes, energy: action.energy }); actionSummary = `Tempo set today to ${action.availableMinutes} available minutes with ${action.energy} energy.`; } else if (action?.type === 'workout_swap') { await db.upsertPlanOverride(user.id, plan.today.date, action.alternative); actionSummary = `Tempo changed today’s workout to ${action.alternative.title}.`; } else if (action?.type === 'log_run') { await db.addWorkout(user.id, { id: crypto.randomUUID(), title: 'Run', type: 'running', outcome: 'completed', durationMinutes: Math.max(0, Math.min(360, action.minutes)), perceivedEffort: action.effort, note: 'Logged through Tempo Coach', details: { running: { distance: action.miles } }, source: 'manual', loggedAt: new Date().toISOString() }); actionSummary = `Tempo logged a ${action.miles}-mile run${action.effort ? ` at effort ${action.effort}` : ''}.`; } plan = await planWithDashboard(user); const workouts = await db.getWorkouts(user.id); const messages = await db.getCoachMessages(user.id); const reply = await createCoachReply({ user, plan, workouts, messages, message, actionSummary }); const assistant = await db.addCoachMessage(user.id, 'assistant', actionSummary ? `${actionSummary} ${reply.content}` : reply.content); return json(response, 200, { message: assistant, mode: reply.mode, action: action?.type || null }); }
  if (request.method === 'GET' && url.pathname === '/api/strava') { const user = await requireUser(request, response); if (!user) return; const connection = await db.getStravaConnection(user.id); return json(response, 200, { configured: strava.configured(), connected: Boolean(connection), athleteId: connection?.athleteId || null }); }
  if (request.method === 'GET' && url.pathname === '/api/strava/connect') { const user = await requireUser(request, response); if (!user) return; if (!strava.configured()) return json(response, 503, { error: 'Strava is not configured yet. Add the Strava values to .env first.' }); const state = crypto.randomBytes(24).toString('hex'); stravaStates.set(state, { userId: user.id, expiresAt: Date.now() + 600000 }); response.writeHead(302, { Location: strava.authorizeUrl(state) }); return response.end(); }
  if (request.method === 'GET' && url.pathname === '/api/strava/callback') { const state = String(url.searchParams.get('state') || ''), code = String(url.searchParams.get('code') || ''), pending = stravaStates.get(state); stravaStates.delete(state); if (!pending || pending.expiresAt < Date.now() || !code) { response.writeHead(302, { Location: '/?strava=failed' }); return response.end(); } try { const token = await strava.exchangeCode(code); await db.upsertStravaConnection(pending.userId, { athleteId: token.athlete.id, accessToken: strava.encrypt(token.access_token), refreshToken: strava.encrypt(token.refresh_token), expiresAt: token.expires_at, scope: token.scope || '' }); await syncStrava(pending.userId); response.writeHead(302, { Location: '/?strava=connected' }); return response.end(); } catch { response.writeHead(302, { Location: '/?strava=failed' }); return response.end(); } }
  if (request.method === 'POST' && url.pathname === '/api/strava/sync') { const user = await requireUser(request, response); if (!user) return; return json(response, 200, { imported: await syncStrava(user.id) }); }
  if (request.method === 'POST' && url.pathname === '/api/strava/disconnect') { const user = await requireUser(request, response); if (!user) return; const connection = await db.getStravaConnection(user.id); if (connection && strava.configured()) { try { await strava.revoke(strava.decrypt(connection.accessToken)); } catch {} } await db.deleteStravaConnection(user.id); return json(response, 200, { ok: true }); }
  return json(response, 404, { error: 'API route not found.' });
}
function serveFile(response, filePath) { fs.readFile(filePath, (error, contents) => { if (error) { response.writeHead(404); response.end('Not found'); return; } response.writeHead(200, { 'Content-Type': path.extname(filePath) === '.html' ? 'text/html; charset=utf-8' : 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'Permissions-Policy': 'geolocation=(), microphone=(), camera=()' }); response.end(contents); }); }
async function start() { await db.initSchema(); await db.purgeExpiredSessions(); http.createServer(async (request, response) => { const url = new URL(request.url, `http://${request.headers.host}`); try { if (request.method === 'GET' && url.pathname === '/health') { await db.healthCheck(); return json(response, 200, { ok: true }); } if (url.pathname.startsWith('/api/')) return await handleApi(request, response, url); if (request.method !== 'GET') { response.writeHead(405); return response.end('Method not allowed'); } return serveFile(response, path.join(ROOT, url.pathname === '/' ? 'index.html' : path.basename(url.pathname))); } catch (error) { const eventId = crypto.randomUUID(); console.error(`[${eventId}]`, error); try { await db.recordAppError({ id: eventId, method: request.method, path: url.pathname, message: String(error.message || error).slice(0, 500) }); } catch (loggingError) { console.error('Could not save app error:', loggingError.message); } return json(response, 500, { error: `Something went wrong. Reference: ${eventId}` }); } }).listen(PORT, '0.0.0.0', () => console.log(`Tempo is running with Neon at http://localhost:${PORT}`)); }
start().catch(error => { console.error('Unable to connect to Neon:', error.message); process.exitCode = 1; });
