/** Tempo server. PostgreSQL data is stored in Neon; sessions stay local for this MVP. */
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const db = require('./db');
const { generatePlan } = require('./plan-engine');
const { createCoachReply } = require('./coach');
const strava = require('./strava');

const PORT = Number(process.env.PORT || 3000);
const ROOT = __dirname;
const sessions = new Map();
const stravaStates = new Map();

function passwordHash(password, salt = crypto.randomBytes(16).toString('hex')) { return `${salt}:${crypto.scryptSync(password, salt, 64).toString('hex')}`; }
function passwordMatches(password, stored) { const [salt, savedHash] = stored.split(':'); return crypto.timingSafeEqual(Buffer.from(savedHash, 'hex'), Buffer.from(passwordHash(password, salt).split(':')[1], 'hex')); }
function publicUser(user) { const { passwordHash: _passwordHash, ...safeUser } = user; return safeUser; }
function parseCookies(request) { return Object.fromEntries((request.headers.cookie || '').split(';').filter(Boolean).map(item => { const index = item.indexOf('='); return [item.slice(0, index).trim(), decodeURIComponent(item.slice(index + 1))]; })); }
async function currentUser(request) { const userId = sessions.get(parseCookies(request).tempo_session); return userId ? db.getUserById(userId) : null; }
function json(response, status, body, cookie) { response.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', ...(cookie ? { 'Set-Cookie': cookie } : {}) }); response.end(JSON.stringify(body)); }
function readJson(request) { return new Promise((resolve, reject) => { let raw = ''; request.on('data', chunk => { raw += chunk; if (raw.length > 100000) request.destroy(); }); request.on('end', () => { try { resolve(raw ? JSON.parse(raw) : {}); } catch { reject(new Error('Please send valid JSON.')); } }); }); }
async function requireUser(request, response) { const user = await currentUser(request); if (!user) { json(response, 401, { error: 'Please sign in first.' }); return null; } return user; }
function validateProfile(profile) { const goals = ['run_stronger', 'build_strength', 'both'], levels = ['new', 'intermediate', 'advanced'], equipment = ['bodyweight', 'home_gym', 'full_gym']; if (!goals.includes(profile.goal)) return 'Choose a valid training goal.'; if (!levels.includes(profile.trainingLevel)) return 'Choose a valid training level.'; if (!equipment.includes(profile.equipment)) return 'Choose valid equipment access.'; if (!Array.isArray(profile.trainingDays) || profile.trainingDays.length < 1 || profile.trainingDays.length > 7) return 'Choose one to seven training days.'; if (!profile.timezone || profile.timezone.length > 80) return 'Provide a valid timezone.'; if (typeof profile.healthConsent !== 'boolean' || typeof profile.aiConsent !== 'boolean') return 'Choose the profile consent options.'; return null; }
function validateWorkout(workout) { const outcomes = ['completed', 'partial', 'skipped']; if (!String(workout.title || '').trim()) return 'Give the workout a short name.'; if (!outcomes.includes(workout.outcome)) return 'Choose whether the workout was completed, partial, or skipped.'; const duration = Number(workout.durationMinutes); if (!Number.isFinite(duration) || duration < 0 || duration > 360) return 'Enter a duration from 0 to 360 minutes.'; const effort = workout.perceivedEffort === '' || workout.perceivedEffort === undefined ? null : Number(workout.perceivedEffort); if (effort !== null && (!Number.isInteger(effort) || effort < 1 || effort > 10)) return 'Effort must be a whole number from 1 to 10.'; if (String(workout.note || '').length > 500) return 'Keep notes to 500 characters or fewer.'; return null; }
function sessionCookie(id) { return `tempo_session=${id}; HttpOnly; SameSite=Lax; Path=/`; }
async function syncStrava(userId) { const connection = await db.getStravaConnection(userId); if (!connection) throw new Error('Connect Strava first.'); const access = await strava.refreshIfNeeded(connection); if (access.refreshed) await db.upsertStravaConnection(userId, { ...access.refreshed, athleteId: connection.athleteId, scope: connection.scope }); const activities = await strava.listActivities(access.accessToken); let imported = 0; for (const activity of activities) { if (await db.hasStravaActivity(activity.id)) continue; const minutes = Math.max(0, Math.round(Number(activity.moving_time || activity.elapsed_time || 0) / 60)); const workout = await db.addWorkout(userId, { id: crypto.randomUUID(), title: activity.name || 'Strava activity', type: activity.sport_type || activity.type || 'activity', outcome: 'completed', durationMinutes: minutes, perceivedEffort: null, note: 'Imported from Strava', source: 'strava', loggedAt: activity.start_date || new Date().toISOString() }); await db.addStravaActivity(userId, activity, workout.id); imported++; } return imported; }
async function planWithDashboard(user) { const workouts = await db.getWorkouts(user.id); const plan = generatePlan(user.profile, { missedToday: user.missedToday, workouts }); const activity = await db.getActivityDashboard(user.id, plan.weekStart, plan.weekEnd, plan.today.date); return { ...plan, dashboard: activity }; }

async function handleApi(request, response, url) {
  if (request.method === 'GET' && url.pathname === '/api/me') { const user = await currentUser(request); return json(response, 200, { user: user ? publicUser(user) : null }); }
  if (request.method === 'POST' && url.pathname === '/api/auth/register') {
    const { name = '', email = '', password = '' } = await readJson(request); const normalizedEmail = email.trim().toLowerCase();
    if (name.trim().length < 2) return json(response, 400, { error: 'Enter your name (at least 2 characters).' }); if (!/^\S+@\S+\.\S+$/.test(normalizedEmail)) return json(response, 400, { error: 'Enter a valid email address.' }); if (password.length < 10) return json(response, 400, { error: 'Use a password with at least 10 characters.' });
    if (await db.getUserByEmail(normalizedEmail)) return json(response, 409, { error: 'An account with that email already exists.' });
    const user = await db.createUser({ id: crypto.randomUUID(), name: name.trim(), email: normalizedEmail, passwordHash: passwordHash(password), role: 'consumer', createdAt: new Date().toISOString() }); const sessionId = crypto.randomBytes(32).toString('hex'); sessions.set(sessionId, user.id); return json(response, 201, { user: publicUser(user) }, sessionCookie(sessionId));
  }
  if (request.method === 'POST' && url.pathname === '/api/auth/login') { const { email = '', password = '' } = await readJson(request); const user = await db.getUserByEmail(email.trim().toLowerCase()); if (!user || !passwordMatches(password, user.passwordHash)) return json(response, 401, { error: 'Email or password is incorrect.' }); const sessionId = crypto.randomBytes(32).toString('hex'); sessions.set(sessionId, user.id); return json(response, 200, { user: publicUser(user) }, sessionCookie(sessionId)); }
  if (request.method === 'POST' && url.pathname === '/api/auth/logout') { sessions.delete(parseCookies(request).tempo_session); return json(response, 200, { ok: true }, 'tempo_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'); }
  if (request.method === 'PUT' && url.pathname === '/api/profile') { const user = await requireUser(request, response); if (!user) return; const profile = await readJson(request), problem = validateProfile(profile); if (problem) return json(response, 400, { error: problem }); const saved = await db.upsertProfile(user.id, { ...profile, sessionMinutes: Number(profile.sessionMinutes) || 45, constraints: profile.healthConsent ? String(profile.constraints || '').slice(0, 1000) : '' }); return json(response, 200, { user: publicUser(saved) }); }
  if (request.method === 'GET' && url.pathname === '/api/plan') { const user = await requireUser(request, response); if (!user) return; if (!user.profile) return json(response, 400, { error: 'Save your coaching profile before generating a plan.' }); return json(response, 200, { plan: await planWithDashboard(user) }); }
  if (request.method === 'POST' && url.pathname === '/api/plan/miss-today') { const user = await requireUser(request, response); if (!user) return; if (!user.profile) return json(response, 400, { error: 'Save your coaching profile before adjusting a plan.' }); const saved = await db.markMissedToday(user.id); return json(response, 200, { plan: await planWithDashboard(saved) }); }
  if (request.method === 'GET' && url.pathname === '/api/workouts') { const user = await requireUser(request, response); if (!user) return; return json(response, 200, { workouts: await db.getWorkouts(user.id) }); }
  if (request.method === 'POST' && url.pathname === '/api/workouts') { const user = await requireUser(request, response); if (!user) return; const workout = await readJson(request), problem = validateWorkout(workout); if (problem) return json(response, 400, { error: problem }); const saved = await db.addWorkout(user.id, { id: crypto.randomUUID(), title: String(workout.title).trim().slice(0, 80), type: String(workout.type || 'other').slice(0, 40), outcome: workout.outcome, durationMinutes: Number(workout.durationMinutes), perceivedEffort: workout.perceivedEffort === '' || workout.perceivedEffort === undefined ? null : Number(workout.perceivedEffort), note: String(workout.note || '').trim().slice(0, 500), source: workout.source === 'plan' ? 'plan' : 'manual', loggedAt: new Date().toISOString() }); return json(response, 201, { workout: saved }); }
  if (request.method === 'GET' && url.pathname === '/api/coach') { const user = await requireUser(request, response); if (!user) return; return json(response, 200, { messages: await db.getCoachMessages(user.id), mode: process.env.OPENAI_API_KEY && user.profile?.aiConsent ? 'ai' : 'preview' }); }
  if (request.method === 'POST' && url.pathname === '/api/coach') { const user = await requireUser(request, response); if (!user) return; if (!user.profile) return json(response, 400, { error: 'Save your coaching profile before talking with Tempo Coach.' }); const body = await readJson(request); const message = String(body.message || '').trim(); if (!message || message.length > 600) return json(response, 400, { error: 'Enter a message between 1 and 600 characters.' }); await db.addCoachMessage(user.id, 'user', message); const workouts = await db.getWorkouts(user.id); const plan = generatePlan(user.profile, { missedToday: user.missedToday, workouts }); const reply = await createCoachReply({ user, plan, workouts, message }); const assistant = await db.addCoachMessage(user.id, 'assistant', reply.content); return json(response, 200, { message: assistant, mode: reply.mode }); }
  if (request.method === 'GET' && url.pathname === '/api/strava') { const user = await requireUser(request, response); if (!user) return; const connection = await db.getStravaConnection(user.id); return json(response, 200, { configured: strava.configured(), connected: Boolean(connection), athleteId: connection?.athleteId || null }); }
  if (request.method === 'GET' && url.pathname === '/api/strava/connect') { const user = await requireUser(request, response); if (!user) return; if (!strava.configured()) return json(response, 503, { error: 'Strava is not configured yet. Add the Strava values to .env first.' }); const state = crypto.randomBytes(24).toString('hex'); stravaStates.set(state, { userId: user.id, expiresAt: Date.now() + 600000 }); response.writeHead(302, { Location: strava.authorizeUrl(state) }); return response.end(); }
  if (request.method === 'GET' && url.pathname === '/api/strava/callback') { const state = String(url.searchParams.get('state') || ''), code = String(url.searchParams.get('code') || ''), pending = stravaStates.get(state); stravaStates.delete(state); if (!pending || pending.expiresAt < Date.now() || !code) { response.writeHead(302, { Location: '/?strava=failed' }); return response.end(); } try { const token = await strava.exchangeCode(code); await db.upsertStravaConnection(pending.userId, { athleteId: token.athlete.id, accessToken: strava.encrypt(token.access_token), refreshToken: strava.encrypt(token.refresh_token), expiresAt: token.expires_at, scope: token.scope || '' }); await syncStrava(pending.userId); response.writeHead(302, { Location: '/?strava=connected' }); return response.end(); } catch { response.writeHead(302, { Location: '/?strava=failed' }); return response.end(); } }
  if (request.method === 'POST' && url.pathname === '/api/strava/sync') { const user = await requireUser(request, response); if (!user) return; return json(response, 200, { imported: await syncStrava(user.id) }); }
  if (request.method === 'POST' && url.pathname === '/api/strava/disconnect') { const user = await requireUser(request, response); if (!user) return; const connection = await db.getStravaConnection(user.id); if (connection && strava.configured()) { try { await strava.revoke(strava.decrypt(connection.accessToken)); } catch {} } await db.deleteStravaConnection(user.id); return json(response, 200, { ok: true }); }
  return json(response, 404, { error: 'API route not found.' });
}
function serveFile(response, filePath) { fs.readFile(filePath, (error, contents) => { if (error) { response.writeHead(404); response.end('Not found'); return; } response.writeHead(200, { 'Content-Type': path.extname(filePath) === '.html' ? 'text/html; charset=utf-8' : 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff' }); response.end(contents); }); }
async function start() { await db.initSchema(); http.createServer(async (request, response) => { const url = new URL(request.url, `http://${request.headers.host}`); try { if (url.pathname.startsWith('/api/')) return await handleApi(request, response, url); if (request.method !== 'GET') { response.writeHead(405); return response.end('Method not allowed'); } return serveFile(response, path.join(ROOT, url.pathname === '/' ? 'index.html' : path.basename(url.pathname))); } catch (error) { console.error(error); return json(response, 500, { error: 'Something went wrong. Check the terminal for details.' }); } }).listen(PORT, () => console.log(`Tempo is running with Neon at http://localhost:${PORT}`)); }
start().catch(error => { console.error('Unable to connect to Neon:', error.message); process.exitCode = 1; });
