/** Tempo server. PostgreSQL data is stored in Neon; sessions stay local for this MVP. */
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const db = require('./db');
const { generatePlan } = require('./plan-engine');

const PORT = Number(process.env.PORT || 3000);
const ROOT = __dirname;
const sessions = new Map();

function passwordHash(password, salt = crypto.randomBytes(16).toString('hex')) { return `${salt}:${crypto.scryptSync(password, salt, 64).toString('hex')}`; }
function passwordMatches(password, stored) { const [salt, savedHash] = stored.split(':'); return crypto.timingSafeEqual(Buffer.from(savedHash, 'hex'), Buffer.from(passwordHash(password, salt).split(':')[1], 'hex')); }
function publicUser(user) { const { passwordHash: _passwordHash, ...safeUser } = user; return safeUser; }
function parseCookies(request) { return Object.fromEntries((request.headers.cookie || '').split(';').filter(Boolean).map(item => { const index = item.indexOf('='); return [item.slice(0, index).trim(), decodeURIComponent(item.slice(index + 1))]; })); }
async function currentUser(request) { const userId = sessions.get(parseCookies(request).tempo_session); return userId ? db.getUserById(userId) : null; }
function json(response, status, body, cookie) { response.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', ...(cookie ? { 'Set-Cookie': cookie } : {}) }); response.end(JSON.stringify(body)); }
function readJson(request) { return new Promise((resolve, reject) => { let raw = ''; request.on('data', chunk => { raw += chunk; if (raw.length > 100000) request.destroy(); }); request.on('end', () => { try { resolve(raw ? JSON.parse(raw) : {}); } catch { reject(new Error('Please send valid JSON.')); } }); }); }
async function requireUser(request, response) { const user = await currentUser(request); if (!user) { json(response, 401, { error: 'Please sign in first.' }); return null; } return user; }
function validateProfile(profile) { const goals = ['run_stronger', 'build_strength', 'both'], levels = ['new', 'intermediate', 'advanced'], equipment = ['bodyweight', 'home_gym', 'full_gym']; if (!goals.includes(profile.goal)) return 'Choose a valid training goal.'; if (!levels.includes(profile.trainingLevel)) return 'Choose a valid training level.'; if (!equipment.includes(profile.equipment)) return 'Choose valid equipment access.'; if (!Array.isArray(profile.trainingDays) || profile.trainingDays.length < 1 || profile.trainingDays.length > 7) return 'Choose one to seven training days.'; if (!profile.timezone || profile.timezone.length > 80) return 'Provide a valid timezone.'; if (typeof profile.healthConsent !== 'boolean') return 'Choose whether you consent to storing optional constraints.'; return null; }
function validateWorkout(workout) { const outcomes = ['completed', 'partial', 'skipped']; if (!String(workout.title || '').trim()) return 'Give the workout a short name.'; if (!outcomes.includes(workout.outcome)) return 'Choose whether the workout was completed, partial, or skipped.'; const duration = Number(workout.durationMinutes); if (!Number.isFinite(duration) || duration < 0 || duration > 360) return 'Enter a duration from 0 to 360 minutes.'; const effort = workout.perceivedEffort === '' || workout.perceivedEffort === undefined ? null : Number(workout.perceivedEffort); if (effort !== null && (!Number.isInteger(effort) || effort < 1 || effort > 10)) return 'Effort must be a whole number from 1 to 10.'; if (String(workout.note || '').length > 500) return 'Keep notes to 500 characters or fewer.'; return null; }
function sessionCookie(id) { return `tempo_session=${id}; HttpOnly; SameSite=Lax; Path=/`; }

async function handleApi(request, response, url) {
  if (request.method === 'GET' && url.pathname === '/api/me') { const user = await currentUser(request); return json(response, 200, { user: user ? publicUser(user) : null }); }
  if (request.method === 'POST' && url.pathname === '/api/auth/register') {
    const { name = '', email = '', password = '' } = await readJson(request); const normalizedEmail = email.trim().toLowerCase();
    if (name.trim().length < 2) return json(response, 400, { error: 'Enter your name (at least 2 characters).' }); if (!/^\S+@\S+\.\S+$/.test(normalizedEmail)) return json(response, 400, { error: 'Enter a valid email address.' }); if (password.length < 10) return json(response, 400, { error: 'Use a password with at least 10 characters.' });
    if (await db.getUserByEmail(normalizedEmail)) return json(response, 409, { error: 'An account with that email already exists.' });
    const user = await db.createUser({ id: crypto.randomUUID(), name: name.trim(), email: normalizedEmail, passwordHash: passwordHash(password), role: 'consumer', createdAt: new Date().toISOString() }); const sessionId = crypto.randomBytes(32).toString('hex'); sessions.set(sessionId, user.id); return json(response, 201, { user: publicUser(user) }, sessionCookie(sessionId));
  }
  if (request.method === 'POST' && url.pathname === '/api/auth/login') { const { email = '', password = '' } = await readJson(request); const user = await db.getUserByEmail(email.trim().toLowerCase()); if (!user || !passwordMatches(password, user.passwordHash)) return json(response, 401, { error: 'Email or password is incorrect.' }); const sessionId = crypto.randomBytes(32).toString('hex'); sessions.set(sessionId, user.id); return json(response, 200, { user: publicUser(user) }, sessionCookie(sessionId)); }
  if (request.method === 'POST' && url.pathname === '/api/auth/logout') { sessions.delete(parseCookies(request).tempo_session); return json(response, 200, { ok: true }, 'tempo_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'); }
  if (request.method === 'PUT' && url.pathname === '/api/profile') { const user = await requireUser(request, response); if (!user) return; const profile = await readJson(request), problem = validateProfile(profile); if (problem) return json(response, 400, { error: problem }); const saved = await db.upsertProfile(user.id, { ...profile, sessionMinutes: Number(profile.sessionMinutes) || 45, constraints: profile.healthConsent ? String(profile.constraints || '').slice(0, 1000) : '' }); return json(response, 200, { user: publicUser(saved) }); }
  if (request.method === 'GET' && url.pathname === '/api/plan') { const user = await requireUser(request, response); if (!user) return; if (!user.profile) return json(response, 400, { error: 'Save your coaching profile before generating a plan.' }); return json(response, 200, { plan: generatePlan(user.profile, { missedToday: user.missedToday, workouts: await db.getWorkouts(user.id) }) }); }
  if (request.method === 'POST' && url.pathname === '/api/plan/miss-today') { const user = await requireUser(request, response); if (!user) return; if (!user.profile) return json(response, 400, { error: 'Save your coaching profile before adjusting a plan.' }); const saved = await db.markMissedToday(user.id); return json(response, 200, { plan: generatePlan(saved.profile, { missedToday: saved.missedToday, workouts: await db.getWorkouts(user.id) }) }); }
  if (request.method === 'GET' && url.pathname === '/api/workouts') { const user = await requireUser(request, response); if (!user) return; return json(response, 200, { workouts: await db.getWorkouts(user.id) }); }
  if (request.method === 'POST' && url.pathname === '/api/workouts') { const user = await requireUser(request, response); if (!user) return; const workout = await readJson(request), problem = validateWorkout(workout); if (problem) return json(response, 400, { error: problem }); const saved = await db.addWorkout(user.id, { id: crypto.randomUUID(), title: String(workout.title).trim().slice(0, 80), type: String(workout.type || 'other').slice(0, 40), outcome: workout.outcome, durationMinutes: Number(workout.durationMinutes), perceivedEffort: workout.perceivedEffort === '' || workout.perceivedEffort === undefined ? null : Number(workout.perceivedEffort), note: String(workout.note || '').trim().slice(0, 500), source: workout.source === 'plan' ? 'plan' : 'manual', loggedAt: new Date().toISOString() }); return json(response, 201, { workout: saved }); }
  return json(response, 404, { error: 'API route not found.' });
}
function serveFile(response, filePath) { fs.readFile(filePath, (error, contents) => { if (error) { response.writeHead(404); response.end('Not found'); return; } response.writeHead(200, { 'Content-Type': path.extname(filePath) === '.html' ? 'text/html; charset=utf-8' : 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff' }); response.end(contents); }); }
async function start() { await db.initSchema(); http.createServer(async (request, response) => { const url = new URL(request.url, `http://${request.headers.host}`); try { if (url.pathname.startsWith('/api/')) return await handleApi(request, response, url); if (request.method !== 'GET') { response.writeHead(405); return response.end('Method not allowed'); } return serveFile(response, path.join(ROOT, url.pathname === '/' ? 'index.html' : path.basename(url.pathname))); } catch (error) { console.error(error); return json(response, 500, { error: 'Something went wrong. Check the terminal for details.' }); } }).listen(PORT, () => console.log(`Tempo is running with Neon at http://localhost:${PORT}`)); }
start().catch(error => { console.error('Unable to connect to Neon:', error.message); process.exitCode = 1; });
