const crypto = require('node:crypto');

function configured() { return Boolean(process.env.STRAVA_CLIENT_ID && process.env.STRAVA_CLIENT_SECRET && process.env.STRAVA_REDIRECT_URI && process.env.STRAVA_TOKEN_KEY); }
function encryptionKey() { const key = Buffer.from(process.env.STRAVA_TOKEN_KEY || '', 'base64'); if (key.length !== 32) throw new Error('STRAVA_TOKEN_KEY must be a base64-encoded 32-byte key.'); return key; }
function encrypt(value) { const iv = crypto.randomBytes(12); const cipher = crypto.createCipheriv('aes-256-gcm', encryptionKey(), iv); const encrypted = Buffer.concat([cipher.update(value, 'utf8'), cipher.final()]); return Buffer.concat([iv, cipher.getAuthTag(), encrypted]).toString('base64'); }
function decrypt(value) { const raw = Buffer.from(value, 'base64'); const decipher = crypto.createDecipheriv('aes-256-gcm', encryptionKey(), raw.subarray(0, 12)); decipher.setAuthTag(raw.subarray(12, 28)); return Buffer.concat([decipher.update(raw.subarray(28)), decipher.final()]).toString('utf8'); }
function authorizeUrl(state) { const params = new URLSearchParams({ client_id: process.env.STRAVA_CLIENT_ID, redirect_uri: process.env.STRAVA_REDIRECT_URI, response_type: 'code', approval_prompt: 'auto', scope: 'activity:read_all', state }); return `https://www.strava.com/oauth/authorize?${params}`; }
async function exchangeCode(code) { const body = new URLSearchParams({ client_id: process.env.STRAVA_CLIENT_ID, client_secret: process.env.STRAVA_CLIENT_SECRET, code, grant_type: 'authorization_code' }); const response = await fetch('https://www.strava.com/oauth/token', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body }); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Strava authorization failed.'); return data; }
async function refreshIfNeeded(connection) { if (Number(connection.expiresAt) > Math.floor(Date.now() / 1000) + 300) return { accessToken: decrypt(connection.accessToken), connection }; const body = new URLSearchParams({ client_id: process.env.STRAVA_CLIENT_ID, client_secret: process.env.STRAVA_CLIENT_SECRET, grant_type: 'refresh_token', refresh_token: decrypt(connection.refreshToken) }); const response = await fetch('https://www.strava.com/oauth/token', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body }); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Could not refresh the Strava connection.'); return { accessToken: data.access_token, refreshed: { accessToken: encrypt(data.access_token), refreshToken: encrypt(data.refresh_token), expiresAt: data.expires_at } };
}
async function listActivities(accessToken) { const response = await fetch('https://www.strava.com/api/v3/athlete/activities?per_page=30', { headers: { Authorization: `Bearer ${accessToken}` } }); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Could not download Strava activities.'); return data; }
async function revoke(accessToken) { await fetch('https://www.strava.com/oauth/revoke', { method: 'POST', headers: { Authorization: `Basic ${Buffer.from(`${process.env.STRAVA_CLIENT_ID}:${process.env.STRAVA_CLIENT_SECRET}`).toString('base64')}`, 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ token: accessToken, token_type_hint: 'access_token' }) }); }
module.exports = { configured, encrypt, decrypt, authorizeUrl, exchangeCode, refreshIfNeeded, listActivities, revoke };
